[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "octoverilog"
version = "0.1.0"
authors = [
  { name="Pan Lu", email="lupantech@gmail.com" },
]
description = "An OctoTools-based workflow for generating and verifying Verilog/SystemVerilog."
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["dependencies"]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[tool.setuptools.packages.find]
where = ["."]
include = ["octotools*"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
OctoTools = "https://github.com/octotools/octotools"
CodeV-R1 = "https://github.com/haoxufeng/CodeV-R1"

[project.scripts]
octoverilog = "octotools.verilog.cli:main"

[project.optional-dependencies]
dev = [
    "black>=25.1.0",
    "isort>=6.0.1"
]

[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"
